# ~/.zprofile - Executed for login shells.

# Add Homebrew to your PATH
# This line is required for Homebrew to work correctly on Apple Silicon Macs.
eval "$(/opt/homebrew/bin/brew shellenv)"

# >>> Codex installer >>>
export PATH="/Users/han/.codex/packages/standalone/bin:$PATH"
# <<< Codex installer <<<
