#!/usr/bin/env bash
# shellcheck disable=SC2034,SC2154

write_shell_env_file() {
    local shell="$1"
    local dest="$2"
    local label="$3"
    local tmp
    local var
    local vars=(
        DOTFILES_DIR
        DOT_ENV_FILE
        DOT_BREWFILES
        DOT_DEFAULT_SHELL
        DOT_ENABLE_DIA
        DOT_ENABLE_ONEPASSWORD
        DOT_ENABLE_SYSTEM_EXTENSIONS
        DOT_ENABLE_CODEX_CONFIG
        DOT_ENABLE_GIT_CONFIG
        TOOLS_HOME
        SKILLS_BASE
        DOT_SKILL_SOURCES
        DOT_PRUNE_EXTRA_SKILLS
        DOT_DIA_APP
        AGENT_BROWSER_DIA_PORT
        CODEX_NODE_REPL_ENV_FILE
        DOT_CODEX_NOTIFY_COMMAND
        DOT_CLOUDSTORAGE_HOME
        DOT_DROPBOX_HOME
        DOT_VAULT_HOME
        DOT_GDRIVE_HOME
        HOMEBREW_NO_ENV_HINTS
        BAT_PAGER
        BAT_STYLE
        EZA_DEFAULT_IGNORE
        BUF_HOME
        CHO_HOME
        FIN_HOME
        GRN_HOME
        LET_HOME
        PDF_HOME
        TAO_HOME
        BUF
        CHO
        FIN
        GRN
        LET
        PDF
        TAO
    )

    if [ -e "$dest" ] || [ -L "$dest" ]; then
        if ! grep -Fq "dotfiles-managed:" "$dest" 2>/dev/null; then
            backup_existing_target "setup.env" "$dest" "backup-generated"
        fi
    fi

    dot_apply mkdir -p "$(dirname "$dest")"

    if dot_dry_run; then
        dot_progress_status "RENDER" "$DOT_PROGRESS_BLUE" "$label -> $dest"
        return 0
    fi

    tmp="$(mktemp "${TMPDIR:-/tmp}/dot-shell-env.XXXXXX")"
    {
        printf '# dotfiles-managed: generated by scripts/setup.sh from setup.env\n'
        printf '# Do not edit directly; update setup.env and rerun setup.\n'
        case "$shell" in
            zsh) printf 'export DOT_ZSH_ENV_FILE=%s\n' "$(dot_shell_quote "$dest")" ;;
            fish) printf 'set -gx DOT_FISH_ENV_FILE %s\n' "$(dot_shell_quote "$dest")" ;;
        esac
        for var in "${vars[@]}"; do
            write_shell_env_var "$shell" "$var"
        done
    } >"$tmp"
    mv "$tmp" "$dest"
    dot_manifest_append "render" "setup.env" "$dest"
    dot_progress_status "RENDER" "$DOT_PROGRESS_BLUE" "$label -> $dest"
}

write_shell_env_files() {
    write_shell_env_file zsh "$HOME/.config/dot/env.zsh" "Zsh env"
    write_shell_env_file fish "$HOME/.config/dot/env.fish" "Fish env"
}

resolve_default_shell_path() {
    case "${DOT_DEFAULT_SHELL:-}" in
        "" | none)
            return 1
            ;;
        zsh)
            if [ -x /bin/zsh ]; then
                printf '%s\n' /bin/zsh
            else
                command -v zsh
            fi
            ;;
        fish)
            if command -v fish >/dev/null 2>&1; then
                command -v fish
            elif [ -x /opt/homebrew/bin/fish ]; then
                printf '%s\n' /opt/homebrew/bin/fish
            elif [ -x /usr/local/bin/fish ]; then
                printf '%s\n' /usr/local/bin/fish
            else
                return 1
            fi
            ;;
        /*)
            printf '%s\n' "$DOT_DEFAULT_SHELL"
            ;;
    esac
}

current_login_shell() {
    local shell=""

    if command -v dscl >/dev/null 2>&1 && [ -n "${USER:-}" ]; then
        shell="$(dscl . -read "/Users/$USER" UserShell 2>/dev/null | awk '{print $2}')"
    fi

    if [ -z "$shell" ]; then
        shell="${SHELL:-}"
    fi

    printf '%s\n' "$shell"
}

ensure_shell_allowed() {
    local shell_path="$1"

    if grep -Fxq "$shell_path" /etc/shells 2>/dev/null; then
        dot_progress_ok "Login shell allowed: $shell_path"
        return 0
    fi

    if dot_dry_run; then
        dot_progress_status "PLAN" "$DOT_PROGRESS_DIM" "printf '%s\\n' '$shell_path' | sudo tee -a /etc/shells >/dev/null"
        return 0
    fi

    if [ ! -t 0 ]; then
        dot_progress_warn "Default shell not in /etc/shells: $shell_path"
        dot_progress_info "Run manually: printf '%s\\n' '$shell_path' | sudo tee -a /etc/shells >/dev/null"
        return 1
    fi

    dot_progress_run "Adding login shell to /etc/shells: $shell_path"
    if printf '%s\n' "$shell_path" | sudo tee -a /etc/shells >/dev/null; then
        dot_progress_ok "Login shell allowed: $shell_path"
    else
        dot_progress_fail "Could not add login shell to /etc/shells: $shell_path"
        return 1
    fi
}

apply_default_shell() {
    local shell_path
    local current_shell
    local login_user

    if [ -z "${DOT_DEFAULT_SHELL:-}" ] || [ "$DOT_DEFAULT_SHELL" = "none" ]; then
        dot_progress_skip "Default login shell (DOT_DEFAULT_SHELL=none)"
        return 0
    fi

    if ! shell_path="$(resolve_default_shell_path)"; then
        dot_progress_fail "Requested default shell is unavailable: $DOT_DEFAULT_SHELL"
        return 1
    fi

    if [ ! -x "$shell_path" ]; then
        dot_progress_fail "Requested default shell is not executable: $shell_path"
        return 1
    fi

    if ! ensure_shell_allowed "$shell_path"; then
        dot_progress_skip "Default login shell unchanged"
        return 0
    fi

    current_shell="$(current_login_shell)"
    if [ "$current_shell" = "$shell_path" ]; then
        dot_progress_ok "Default login shell already set: $shell_path"
        return 0
    fi

    if dot_dry_run; then
        dot_progress_status "PLAN" "$DOT_PROGRESS_DIM" "chsh -s $shell_path $(id -un)"
        return 0
    fi

    if [ ! -t 0 ]; then
        dot_progress_warn "Default login shell is $current_shell; expected $shell_path"
        dot_progress_info "Run manually: chsh -s '$shell_path' '$(id -un)'"
        return 0
    fi

    login_user="$(id -un)"
    dot_progress_run "Setting default login shell: $shell_path"
    chsh -s "$shell_path" "$login_user" >/dev/null
    dot_progress_ok "Default login shell set: $shell_path"
}

cleanup_legacy_fish_split() {
    local dest

    for dest in "$HOME"/.config/fish/conf.d/*.fish; do
        [ -e "$dest" ] || [ -L "$dest" ] || continue
        remove_legacy_managed_link "$dest" "$DOTFILES_DIR/shell/fish/conf.d"
    done

    for dest in "$HOME"/.config/fish/functions/*.fish; do
        [ -e "$dest" ] || [ -L "$dest" ] || continue
        remove_legacy_managed_link "$dest" "$DOTFILES_DIR/shell/fish/functions"
    done

    remove_empty_legacy_dir "$HOME/.config/fish/conf.d"
    remove_empty_legacy_dir "$HOME/.config/fish/functions"
}
