# Starship prompt - clean pipe-separated layout
# Foreground-only styling prevents lingering background blocks in terminals.
format = "$directory$git_branch$git_commit$git_state$git_status$nodejs$python$jobs$cmd_duration$status$line_break$character"

[directory]
truncation_length = 3
truncate_to_repo = false
format = "[$path]($style)"
style = "bold fg:#e5e5e5"
home_symbol = "~"
read_only = " [ro]"

[git_branch]
format = "[ | $symbol$branch(:$remote_branch)]($style)"
symbol = "git:"
style = "fg:#d0d0d0"
truncation_length = 20
truncation_symbol = "…"

[git_commit]
format = "[ | @$hash_abbrev]($style)"
style = "fg:#d0d0d0"
commit_hash_length = 7
only_detached = true

[git_state]
format = "[ | $state( $progress_current/$progress_total)]($style)"
style = "bold fg:#b0b0b0"
rebase = "REBASE"
merge = "MERGE"
revert = "REVERT"
cherry_pick = "CHERRY"
bisect = "BISECT"
am = "AM"
am_or_rebase = "AM/REBASE"

[git_status]
format = "[ | $all_status$ahead_behind]($style)"
style = "fg:#b0b0b0"
conflicted = "conflicts:${count} "
ahead = "↑${count} "
behind = "↓${count} "
diverged = "↑${ahead_count}↓${behind_count} "
up_to_date = ""
untracked = "untracked:${count} "
stashed = "stashed:${count} "
modified = "modified:${count} "
staged = "staged:${count} "
renamed = "renamed:${count} "
deleted = "deleted:${count} "

[nodejs]
format = "[ | node:$version]($style)"
style = "fg:#a8a8a8"
detect_extensions = ["js", "mjs", "cjs", "ts", "mts", "cts"]
detect_files = ["package.json", ".node-version", ".nvmrc"]
detect_folders = ["node_modules"]
disabled = false
not_capable_style = "fg:#a8a8a8"

[python]
format = "[ | py:${version}]($style)"
style = "fg:#a8a8a8"
detect_extensions = ["py"]
detect_files = ["requirements.txt", "pyproject.toml", "Pipfile", ".python-version"]
detect_folders = ["venv", ".venv", "__pycache__"]
disabled = false

[jobs]
format = " | jobs:$number"
style = "dimmed white"
symbol = ""
number_threshold = 1
symbol_threshold = 1

[cmd_duration]
min_time = 5000
format = " | took $duration"
style = "dimmed white"
show_milliseconds = false
show_notifications = false

[status]
format = " | ✗ $status"
style = "bold red"
symbol = ""
success_symbol = ""
not_executable_symbol = "✗ not_exec "
not_found_symbol = "✗ not_found "
sigint_symbol = "✗ sigint "
signal_symbol = "✗ signal "
map_symbol = false
disabled = false

[character]
success_symbol = "[›](white)"
error_symbol = "[›](bold red)"
vimcmd_symbol = "[‹](white)"
vimcmd_visual_symbol = "[‹](dimmed white)"

[username]
format = "[ | $user]($style)"
style_user = "fg:#d0d0d0"
style_root = "bold fg:#d0d0d0"
show_always = false
disabled = false

[hostname]
format = "[ | @$hostname]($style)"
style = "fg:#d0d0d0"
ssh_only = true
ssh_symbol = ""
disabled = false

[time]
disabled = true

[package]
disabled = true

[bun]
disabled = true

[rust]
disabled = true

[golang]
disabled = true

[ruby]
disabled = true

[java]
disabled = true

[php]
disabled = true

[dotnet]
disabled = true

[swift]
disabled = true

[zig]
disabled = true

[nim]
disabled = true

[lua]
disabled = true

[perl]
disabled = true

[elixir]
disabled = true

[erlang]
disabled = true

[haskell]
disabled = true

[julia]
disabled = true

[kotlin]
disabled = true

[scala]
disabled = true

[dart]
disabled = true

[deno]
disabled = true

[ocaml]
disabled = true

[crystal]
disabled = true

[vlang]
disabled = true

[vagrant]
disabled = true

[nix_shell]
disabled = true

[conda]
disabled = true

[aws]
disabled = true

[gcloud]
disabled = true

[azure]
disabled = true

[kubernetes]
disabled = true

[terraform]
disabled = true

[docker_context]
disabled = true

[battery]
disabled = true

[memory_usage]
disabled = true
